openapi: 3.0.0
info:
  title: Generic Household
  version: 3.1.0
servers:
  - url: 'http://www.hmislynk.com/global-household-api/rest'
paths:
  /generic-households:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  - genericHouseHoldId: asdf-asdf-assdfasfd-df
                    headOfHouseholdId: asdf-asdf-assdfasfd-dd
                    dateCreated: 2016-06-06
                    dateUpdated: 2016-06-06
                    userCreate: asdf-adf-asdsf
                    userUpdate: asdf-adfasf-asdfasds
                  - genericHouseHoldId: asdf-asdf-assdfasfd-da
                    headOfHouseholdId: asdf-asdf-assdfasfd-dd-sadf
                    dateCreated: 2016-06-06
                    dateUpdated: 2016-06-06
                    userCreate: asdf-adf-asdsf
                    userUpdate: asdf-adfasf-asdfasds
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errorMessage: internal server error
      description: gets a set of generic households
      operationId: GET_generic-households
      parameters:
        - name: inactive
          in: query
          description: Filter the list of generic household by inactive status.
          schema:
            type: boolean
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  - genericlHouseHoldId: asdf-asdf-assdfasfd-df
                    headOfHouseholdId: asdf-asdf-assdfasfd-dd
                    dateCreated: 2016-06-06
                    dateUpdated: 2016-06-06
                    userCreate: asdf-adf-asdsf
                    userUpdate: asdf-adfasf-asdfasds
                  - genericlHouseHoldId: asdf-asdf-assdfasfd-da
                    headOfHouseholdId: asdf-asdf-assdfasfd-dd-sadf
                    dateCreated: 2016-06-06
                    dateUpdated: 2016-06-06
                    userCreate: asdf-adf-asdsf
                    userUpdate: asdf-adfasf-asdfasds
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Resource not found
      description: saves the multiple generic household data.
      operationId: POST_generic-households
      requestBody:
        content:
          application/json:
            example:
              - headOfHouseholdId: asdf-asdf-assdfasfd-dd
              - headOfHouseholdId: asdf-asdf-assdfasfd-dd-sadf
            schema:
              $ref: '#/components/schemas/generic_households'
        required: true
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  - genericlHouseHoldId: asdf-asdf-assdfasfd-df
                    headOfHouseholdId: asdf-asdf-assdfasfd-dd
                    dateCreated: 2016-06-06
                    dateUpdated: 2016-06-06
                    userCreate: asdf-adf-asdsf
                    userUpdate: asdf-adfasf-asdfasds
                  - genericlHouseHoldId: asdf-asdf-assdfasfd-da
                    headOfHouseholdId: asdf-asdf-assdfasfd-dd-sadf
                    dateCreated: 2016-06-06
                    dateUpdated: 2016-06-06
                    userCreate: asdf-adf-asdsf
                    userUpdate: asdf-adfasf-asdfasds
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Resource not found
      description: update the multiple generic household data.
      operationId: PUT_generic-households
      requestBody:
        content:
          application/json:
            example:
              - genericlHouseHoldId: asdf-asdf-assdfasfd-df
                headOfHouseholdId: asdf-asdf-assdfasfd-dd
              - genericlHouseHoldId: asdf-asdf-assdfasfd-da
                headOfHouseholdId: asdf-asdf-assdfasfd-dd-sadf
            schema:
              $ref: '#/components/schemas/generic_households_ids'
        required: true
  '/generic-households/{generic_household_id}':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  genericlHouseHoldId: null
                  headOfHouseholdId: asdf-asdf-assdfasfd-dd
                  dateCreated: 2016-06-06
                  dateUpdated: 2016-06-06
                  userCreate: asdf-adf-asdsf
                  userUpdate: asdf-adfasf-asdfasds
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errorMessage: internal server error
      description: retreives generic household  details.
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: household successfully deleted
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Internal Server Error - retry request'
      description: to delete generic household on the basis of uuid
      operationId: DELETE_generic-households-generic_household_id
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: household successfully updated
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Internal Server Error - retry request'
      description: for updating generic housing data.
      operationId: PUT_generic-households-generic_household_id
      requestBody:
        content:
          application/json:
            example:
              genericlHouseHoldId: bsdf-asdf-assdfasfd-dd
              headOfHouseholdId: asdf-asdf-assdfasfd-dd
              dateCreated: 2016-06-06
              dateUpdated: 2016-06-06
              userCreate: asdf-adf-asdsf
              userUpdate: asdf-adfasf-asdfasds
            schema:
              $ref: '#/components/schemas/generic_household_id'
        required: true
    parameters:
      - name: generic_household_id
        in: path
        required: true
        schema:
          type: string
  '/generic-households/{generic_household_id}/members':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  links:
                  - rel: self
                    href: http://www.hmislynk.com/global-household-api/generic-households/7667b25f-102b-4aa6-8ce4-e714be2f98b5/members
                  content:
                  - householdMembershipId: 61acf5ba-8428-435e-9e89-bd2d68bc508a
                    dateCreated: 2018-12-05 04:06
                    dateUpdated: 2018-12-05 04:06
                    userId: 8b6c6ef2-87c7-47f0-8874-4cca6f09365c
                    genericClientId: 08bd3d50-cb87-41ac-8b64-b3dc3853c411
                    genericHouseholdId: 7667b25f-102b-4aa6-8ce4-e714be2f98b5
                    links:
                    - rel: "/hmis-clientapi/rest/v2015/clients/08bd3d50-cb87-41ac-8b64-b3dc3853c411"
                      href: client
                  - householdMembershipId: ca4c5505-5be0-4fca-821d-e7f74e131347
                    dateCreated: 2018-12-05 04:06
                    dateUpdated: 2018-12-05 04:06
                    relationshipToHeadOfHousehold: Testing
                    userId: 8b6c6ef2-87c7-47f0-8874-4cca6f09365c
                    genericClientId: 91746d23-3b98-4d43-9724-f1c0f2948784
                    genericHouseholdId: 7667b25f-102b-4aa6-8ce4-e714be2f98b5
                    links:
                    - rel: "/hmis-clientapi/rest/v2015/clients/91746d23-3b98-4d43-9724-f1c0f2948784"
                      href: client
                  page:
                    size: 20
                    totalElements: 2
                    totalPages: 1
                    number: 0

        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Resource not found
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: 'address is updated '
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Resource not found
      operationId: POST_generic-households-generic_household_id-members
      requestBody:
        content:
          application/json:
            example:
              $schema: 'http://json-schema.org/draft-04/schema#'
              id: 'http://jsonschema.net'
              type: array
              items:
                - id: householdMemberID
                  type: object
                  properties:
                    houseHoldMembershipId:
                      id: 'http://jsonschema.net/houseHoldMembershipId'
                      type: string
                    genericClientId:
                      id: 'http://jsonschema.net/globalClientId'
                      type: string
                    relationshipToHeadOfHouseHold:
                      id: 'http://jsonschema.net/relationshipToHeadOfHousehold'
                      type: integer
                    dateCreate:
                      id: 'http://jsonschema.net/dateCreate'
                      type: string
                    dateUpdate:
                      id: 'http://jsonschema.net/dateUpdate'
                      type: string
                    userCreate:
                      id: 'http://jsonschema.net/userCreate'
                      type: string
                    userUpdate:
                      id: 'http://jsonschema.net/userUpdate'
                      type: string
                  required:
                    - houseHoldMembershipId
                    - genericClientId
                    - relationshipToHeadOfHousehold
                    - dateCreate
                    - dateUpdate
                    - userCreate
                    - userUpdate
              required:
                - householdMemberID
            schema:
              type: string
        required: true
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: 'members updated '
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Resource not found
      operationId: PUT_generic-households-generic_household_id-members
      requestBody:
        content:
          application/json:
            example:
              - houseHoldMembershipId: 1sdf-sad2-daf23
                genericClientId: asdf-sad2-daf23
                relationshipToHeadOfHousehold: 1
                dateCreate: 2016-06-06
                dateUpdate: 2016-06-06
                userCreate: asd-adf-dsf7
                userUpdate: asdf-as6-asdf-aas
                genericlHouseHoldId: sadf-adf-adf
              - houseHoldMembershipId: 2sdf-sad2-daf23
                genericClientId: asdf-sad2-daf23
                relationshipToHeadOfHousehold: 2
                dateCreate: 2016-06-06
                dateUpdate: 2016-06-06
                userCreate: asd-adf-dsf7
                userUpdate: asdf-as6-asdf-aas
                genericlHouseHoldId: sadf-adf-adf
            schema:
              $ref: '#/components/schemas/household_members_ids'
        required: true
    parameters:
      - name: generic_household_id
        in: path
        required: true
        schema:
          type: string
  '/generic-households/{generic_household_id}/members/{member_id}':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  genericClientId: asdf-sad2-daf23
                  relationshipToHeadOfHousehold: 1
                  dateCreate: 2016-06-06
                  dateUpdate: 2016-06-06
                  userCreate: asd-adf-dsf7
                  userUpdate: asdf-as6-asdf-aas
                  genericlHouseHoldId: sadf-adf-adf
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Resource not found
      description: get the member record based on member_id.
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: member successfully updated.
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Resource not found
      description: update the member record.
      operationId: PUT_generic-households-generic_household_id-members-member_id
      requestBody:
        content:
          application/json:
            example:
              genericClientId: asdf-sad2-daf23
              relationshipToHeadOfHousehold: 1
              dateCreate: 2016-06-06
              dateUpdate: 2016-06-06
              userCreate: asd-adf-dsf7
              userUpdate: asdf-as6-asdf-aas
              genericlHouseHoldId: sadf-adf-adf
            schema:
              $ref: '#/components/schemas/household_members_id'
        required: true
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: member deleted successfully.
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: ' Unauthorized'
        '500':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Resource not found
      description: delete the household member.
      operationId: DELETE_generic-households-generic_household_id-members-member_id
    parameters:
      - name: member_id
        in: path
        required: true
        schema:
          type: string
      - name: generic_household_id
        in: path
        required: true
        schema:
          type: string
components:
  schemas:
    generic_household:
      required:
        - genericlHouseHoldId
        - headOfHouseholdId
        - dateCreated
        - dateUpdated
        - userCreate
        - userUpdate
      type: object
      properties:
        genericlHouseHoldId:
          type: string
        headOfHouseholdId:
          type: string
        dateCreated:
          type: string
        dateUpdated:
          type: string
        userCreate:
          type: string
        userUpdate:
          type: string
    generic_household_id:
      required:
        - genericlHouseHoldId
        - headOfHouseholdId
        - dateCreated
        - dateUpdated
        - userCreate
        - userUpdate
      type: object
      properties:
        genericlHouseHoldId:
          type: string
        headOfHouseholdId:
          type: string
        dateCreated:
          type: string
        dateUpdated:
          type: string
        userCreate:
          type: string
        userUpdate:
          type: string
    generic_households:
      type: array
      items:
        type: string
    generic_households_ids:
      type: array
      items:
        type: string
    household_member:
      required:
        - houseHoldMembershipId
        - genericClientId
        - dateCreate
        - dateUpdate
        - userCreate
        - userUpdate
      type: object
      properties:
        houseHoldMembershipId:
          type: string
        genericClientId:
          type: string
        relationshipToHeadOfHouseHold:
          type: string
        dateCreate:
          type: string
        dateUpdate:
          type: string
        userCreate:
          type: string
        userUpdate:
          type: string
    household_members_id:
      required:
        - houseHoldMembershipId
        - genericClientId
        - dateCreate
        - dateUpdate
        - userCreate
        - userUpdate
      type: object
      properties:
        houseHoldMembershipId:
          type: string
        genericClientId:
          type: string
        relationshipToHeadOfHouseHold:
          type: integer
        dateCreate:
          type: string
        dateUpdate:
          type: string
        userCreate:
          type: string
        userUpdate:
          type: string
    household_members:
      type: array
      items:
        type: string
    household_members_ids:
      type: array
      items:
        required:
          - houseHoldMembershipId
          - genericClientId
          - dateCreate
          - dateUpdate
          - userCreate
          - userUpdate
        type: object
        properties:
          houseHoldMembershipId:
            type: string
          genericClientId:
            type: string
          relationshipToHeadOfHouseHold:
            type: integer
          dateCreate:
            type: string
          dateUpdate:
            type: string
          userCreate:
            type: string
          userUpdate:
            type: string
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    oauth_2_0:
      description: |
        The HMIS API supports OAuth 2.0 for authenticating all API requests.
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://hmislynk.com/hmis-authorization-service/rest/token'
          scopes:
            user: ''
            administrator: ''
  links: {}
  callbacks: {}
